### ISSUE TITLE
Compatibility with MacOSX and python 3.7

### ISSUE THREAD

**Issue by BoPeng** [ansible/ansible-jupyter-kernel#84]
**Describe the bug**
ansible kernel hangs under MacOSX and python 3.7.

**To Reproduce**
Create a fresh conda environent, and ansible kernel does not work.

```
$ conda create -n ansible python=3.7
$ pip install ansible-kernel
$ python -m ansible_kernel.install
$ jupyter notebook
[W 11:50:09.718 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 11:50:09.720 NotebookApp] The port 8888 is already in use, trying another port.
[I 11:50:09.720 NotebookApp] The port 8889 is already in use, trying another port.
[I 11:50:09.728 NotebookApp] Serving notebooks from local directory: /Users/bpeng1
[I 11:50:09.728 NotebookApp] The Jupyter Notebook is running at:
[I 11:50:09.728 NotebookApp] http://bcbm-bpeng.mdanderson.edu:8890/
[I 11:50:09.728 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 11:50:14.887 NotebookApp] Creating new notebook in
[I 11:50:15.881 NotebookApp] Kernel started: cae4aef6-83f6-4f08-89ec-1d9e3262f363
/Users/bpeng1/anaconda3/envs/ansible/lib/python3.7/site-packages/ansible_kernel/modules.py:4: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  modules = yaml.load(f.read())
/Users/bpeng1/anaconda3/envs/ansible/lib/python3.7/site-packages/ansible_kernel/module_args.py:4: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  module_args = yaml.load(f.read())
[W 11:51:15.951 NotebookApp] Timeout waiting for kernel_info reply from cae4aef6-83f6-4f08-89ec-1d9e3262f363
[I 11:52:16.453 NotebookApp] Saving file at /Untitled.ipynb
^C[I 11:52:52.442 NotebookApp] interrupted

```

**Screenshots**
![image](https://user-images.githubusercontent.com/9889312/64977156-7c9f4a80-d878-11e9-8b8c-aacaf0ffedc2.png)

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser Chrome
 - Jupyter Notebook Version: 6.0.1

**Comment by BoPeng** [comment]
Does not work under linux either
```
(ansible) [bpeng1@localhost ~]$ conda create -n ansible python=3.7
(ansible) [bpeng1@localhost ~]$ pip install ansible-kernel
(ansible) [bpeng1@localhost ~]$ python -m ansible_kernel.install
Installing IPython kernel spec
/home/bpeng1/anaconda3/envs/ansible/lib/python3.7/site-packages/ansible_kernel/install.py:26: DeprecationWarning: replace is ignored. Installing a kernelspec always replaces an existing installation
  td, 'ansible', user=user, replace=True, prefix=prefix)
(ansible) [bpeng1@localhost ~]$ jupyter notebook
[I 13:42:10.274 NotebookApp] Writing notebook server cookie secret to /home/bpeng1/.local/share/jupyter/runtime/notebook_cookie_secret
[I 13:42:10.488 NotebookApp] Serving notebooks from local directory: /home/bpeng1
[I 13:42:10.489 NotebookApp] The Jupyter Notebook is running at:
[I 13:42:10.489 NotebookApp] http://localhost:8888/?token=af98f5e99043d650af86725dc1026c330f86648182068cd0
[I 13:42:10.489 NotebookApp]  or http://127.0.0.1:8888/?token=af98f5e99043d650af86725dc1026c330f86648182068cd0
[I 13:42:10.489 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:42:10.576 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/bpeng1/.local/share/jupyter/runtime/nbserver-12886-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=af98f5e99043d650af86725dc1026c330f86648182068cd0
     or http://127.0.0.1:8888/?token=af98f5e99043d650af86725dc1026c330f86648182068cd0
[I 13:42:19.291 NotebookApp] Creating new notebook in 
[I 13:42:19.301 NotebookApp] Writing notebook-signing key to /home/bpeng1/.local/share/jupyter/notebook_secret
[I 13:42:20.396 NotebookApp] Kernel started: e82625dc-8646-4993-aa1f-bcb1df6d15dc
/home/bpeng1/anaconda3/envs/ansible/lib/python3.7/site-packages/ansible_kernel/modules.py:4: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  modules = yaml.load(f.read())
/home/bpeng1/anaconda3/envs/ansible/lib/python3.7/site-packages/ansible_kernel/module_args.py:4: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  module_args = yaml.load(f.read())
Traceback (most recent call last):
  File "/home/bpeng1/anaconda3/envs/ansible/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/bpeng1/anaconda3/envs/ansible/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bpeng1/anaconda3/envs/ansible/lib/python3.7/site-packages/ansible_kernel/__main__.py", line 6, in <module>
    IPKernelApp.launch_instance(kernel_class=AnsibleKernel)

```

**Comment by BoPeng** [comment]
https://github.com/ansible/ansible-jupyter-kernel/issues/84

Seems that Ansible kernel is no longer maintained (no commits and bug fix for two years). I will re-open this ticket after the aforementioned ticket from upstream is addressed.
