### ISSUE TITLE
AttributeError: 'AnsibleKernel' object has no attribute 'user_ns'

### ISSUE THREAD

**Issue by tepene** [ansible/ansible-jupyter-kernel#88]
**Describe the bug**
I can't run the simplest ansible task "debug:" in my notebook. I see the following error in my terminal: **AttributeError: 'AnsibleKernel' object has no attribute 'user_ns'**. Error already occurs when i select the ansible kernel for my notebook.
Am I missing something. Tried to follow the installation guide with the Demo example.

**To Reproduce**

1. pipenv shell
2. pipenv install ansible-kernel
3. python -m ansible_kernel.install
4. jupyter-lab
5. run "debug:" task with ansible kernel
6. See error "AttributeError: 'AnsibleKernel' object has no attribute 'user_ns'" in terminal, no output in notebook

**Expected behavior**
Output like in the [Demo Video](https://github.com/ansible/ansible-jupyter-kernel#demo)

**Desktop:**
 - Ubuntu Budgie 20.04
 - Firefox 82.0.3
```
$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.1.5
qtconsole        : 4.7.7
ipython          : 7.19.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.9
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
```

**Additional context**
Complete Error Message:
```
[I 08:43:51.384 LabApp] Kernel started: ecaa3e34-69ff-4142-a632-6606305e905e, name: ansible
/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/ansible_kernel/modules.py:4: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  modules = yaml.load(f.read())
/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/ansible_kernel/module_args.py:4: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  module_args = yaml.load(f.read())
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/ansible_kernel/__main__.py", line 6, in <module>
    IPKernelApp.launch_instance(kernel_class=AnsibleKernel)
  File "/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 582, in initialize
    self.init_kernel()
  File "/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 444, in init_kernel
    kernel = kernel_factory(parent=self, session=self.session,
  File "/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/traitlets/config/configurable.py", line 537, in instance
    inst = cls(*args, **kwargs)
  File "/home/lus/Code/Jupyter/.venv/lib/python3.8/site-packages/ansible_kernel/kernel.py", line 188, in __init__
    user_ns=self.user_ns,
AttributeError: 'AnsibleKernel' object has no attribute 'user_ns'
```

**Comment by jakabk** [comment]
The same error, installed with pipx.

jupyter core     : 4.7.0
jupyter-notebook : 6.1.5
qtconsole        : 5.0.1
ipython          : 7.19.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.9
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5

**Comment by miketzian** [comment]
Add "self.user_ns = {}" on line 185 in kernel.py and it'll work
I see other issues in running this (or more debug output than I'd like), but seems like this one is a bug rather than any incompatibility.
